// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helloworld.proto
// Protobuf Java Version: 4.31.1

package io.grpc.examples.helloworld;

@com.google.protobuf.Generated
public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.grpc.examples.helloworld.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
